version: '3'

services:
  postgres:
    image: postgres:14.6-alpine3.17
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./data/postgres/14/database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:6.2-alpine3.17
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./data/redis/database_data:/data

  greenlight-v3:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:v3
    container_name: greenlight-v3
    restart: unless-stopped
    env_file: .env
    ports:
      - 127.0.0.1:5050:3000
    logging:
      driver: journald
    volumes:
      - ./log:/usr/src/app/log
      - ./data/greenlight-v3/storage:/usr/src/app/storage
      - ./data/customization/application.bootstrap.scss:/usr/src/app/app/assets/stylesheets/application.bootstrap.scss
      - ./data/customization/HomePage.jsx:/usr/src/app/app/javascript/components/home/HomePage.jsx
      - ./data/customization/Logo.jsx:/usr/src/app/app/javascript/components/shared_components/Logo.jsx
      - ./data/customization/NavbarSignedIn.jsx:/usr/src/app/app/javascript/components/home/NavbarSignedIn.jsx
      - ./data/customization/useDeleteSession.jsx:/usr/src/app/app/javascript/hooks/mutations/sessions/useDeleteSession.jsx
      - ./data/customization/App.jsx:/usr/src/app/app/javascript/App.jsx
      - ./data/customization/application.html.erb:/usr/src/app/app/views/layouts/application.html.erb
      - ./data/customization/user.rb:/usr/src/app/app/models/user.rb
    depends_on:
      - postgres
      - redis
