version: '3'

services:
  postgres:
    image: postgres:14.6-alpine3.17
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./data/postgres/14/database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:6.2-alpine3.17
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./data/redis/database_data:/data

  greenlight-v3:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:v3
    container_name: greenlight-v3
    restart: unless-stopped
    env_file: .env
    ports:
      - 127.0.0.1:5050:3000
    logging:
      driver: journald
    volumes:
      - ./log:/usr/src/app/log
      - ./data/greenlight-v3/storage:/usr/src/app/storage
      - ./data/customization/application.bootstrap.scss:/usr/src/app/app/assets/stylesheets/application.bootstrap.scss
      - ./data/customization/background.png:/usr/src/app/app/assets/images/background.png
      - ./data/customization/SigninForm.jsx:/usr/src/app/app/javascript/components/users/authentication/forms/SigninForm.jsx
      - ./data/customization/SignIn.jsx:/usr/src/app/app/javascript/components/users/authentication/SignIn.jsx
      - ./data/customization/Logo.jsx:/usr/src/app/app/javascript/components/shared_components/Logo.jsx
      - ./data/customization/env_controller.rb:/usr/src/app/app/controllers/api/v1/env_controller.rb
    depends_on:
      - postgres
      - redis
